
services:
  frontend:
    build:
      context: .                     
      dockerfile: Dockerfile.dev     
    volumes:
      - .:/app                      
      - /app/node_modules           
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api 
    command: npm run dev -- --host 0.0.0.0     
